version: "3.2"
services:
  web:
    build: .
    command: ["node", "index.js"]
    networks:
      - backend
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3001"
    environment:
      mongoDbUrl: mongodb://127.0.0.1:27017/WIMPv2
      PORT: 3001
      MESSAGING_QUEUE_ID: user_queue
      MESSAGING_QUEUE_BASEURL: localhost
      MESSAGING_QUEUE_PORT: 5673

